extraction:
  error_handling:
    log_errors: true
    retry_count: 3
  llm:
    config_path: D:/work/code/python/sharebook/config/llm_config.py
    max_tokens: 2000
    temperature: 0.4
    timeout: 30
  parallel:
    max_analyzer_agents: 6
    max_csv_agents: 6
  paths:
    config_path: src/services/extraction_character/config.yaml
    csv_path: D:/work/code/python/sharebook2/data/characters/characters.csv
    novel_path: D:/work/code/python/sharebook2/data/cleaned_novel
  progress:
    current_chapter: 第三十六章 红千叶要反了？.txt
    last_update_time: '2025-11-15T12:33:59.522624'
    processed_chapters:
    - 第一章 遇强则强.txt
    - 第二章 震惊全宗！.txt
    - 第三章 签到奖励！.txt
    - 第四章修为又升！送上门的经验包！.txt
    - 第五章我儿陈枭有成仙之姿！.txt
    - 第六章 收徒，魔教教主？.txt
    - 第七章 绝望的魔教教主.txt
    - 第八章 收徒！获得葬天棺！.txt
    - 第九章 运气好捡到的.txt
    - 第十章 魔教教主哭了.txt
    - 第十一章 找出幕后真凶！.txt
    - 第十二章 猜拳决生死.txt
    - 第十三章 难道是他？.txt
    - 第十四章 继续调教魔教教主.txt
    - 第十五章 弹指杀元婴！.txt
    - 第十六章 变态的血魔！.txt
    - 第十七章 师尊救我！.txt
    - 第十八章 大展神威！.txt
    - 第十九章 任务奖励，至尊骨！.txt
    - 第二十章 奇怪的姿势？.txt
    - 第二十一章 外来修士的强大！.txt
    - 第二十二章 为荒州尊严而战！.txt
    - 第二十三章 你是那个煞笔的儿子？.txt
    - 第二十四章 陈枭怀疑人生.txt
    - 第二十五章 跟我们闹着玩呢？.txt
    - 第二十六章 上苍劫光！.txt
    - 第二十七章 葬天棺，出！.txt
    - 第二十八章 罗天秘境签到！.txt
    - 第二十九章 大罗仙体问世！.txt
    - 第三十章 天帝法相显威！.txt
    - 第三十一章 不要吃鼠鼠！.txt
    - 第三十二章 秘境崩溃！.txt
    - 第三十三章 十万原住民臣服！.txt
    - 第三十四章 名声大噪！.txt
    - 第三十五章 白小汐的人类形态？辣眼睛！.txt
    - 第三十六章 红千叶要反了？.txt
